### ISSUE TITLE
[MedievalFactions] Task #55 for MedievalFactions v4.4-beta-1 generated an exception

### ISSUE THREAD

**Issue by MrDciBelia** [Dans-Plugins/Medieval-Factions#1220]
I try install for the first time mf and i have error on my log

![Screenshot_20211203_171037](https://user-images.githubusercontent.com/94740517/144638051-463ab15e-71d5-4e31-9d6d-cdf60a7b8b17.jpg)

Problem with dynmap and spam always

**Comment by MrDciBelia** [comment]
this error was on the version v4.4-beta-1, i uninstall this version, well install version v4.3 but still the same error.

**Comment by Mr-Deej** [comment]
this also may have been fixed in v4.5.1

**Comment by dmccoystephenson** [comment]
Are you still experiencing this error on v4.5.1? @MrDciBelia
