### ISSUE TITLE
Fix null pointer exception occurring because "this.marerAPI" is null in 1.18.x

### ISSUE THREAD

**Issue by Yalat** [Dans-Plugins/Medieval-Factions#1223]
![image](https://user-images.githubusercontent.com/95971241/145680388-77c69947-93e0-48c0-9b80-cdb4fed7aa21.png)

**Comment by Mr-Deej** [comment]
Was this also fixed in release v4.5.1

**Comment by dmccoystephenson** [comment]
Something similar to this is happening now:
> Cannot invoke "org.dynmap.DynmapCore.getMarkerAPI()" because "this.core" is null
