### ISSUE TITLE
Fix block duplication bug with gates.

### ISSUE THREAD

**Issue by Elafir** [Dans-Plugins/Medieval-Factions#1258]
if you use a piston to push a block out of a gate and then open and close the gate you'll dupe the block.

**Comment by kipper55** [comment]
The blocks are also able to be duped by tnting them and then opening and closing the gate. You can pick the blown up items and repeat. While less efficient, it is still a problem.

**Comment by dmccoystephenson** [comment]
Thanks for the info @kipper55.
