### ISSUE TITLE
Fix players getting teleported to each other’s faction homes if they initiate the home command at the same time.

### ISSUE THREAD

**Issue by dmccoystephenson** [Dans-Plugins/Medieval-Factions#1322]
**Describe the bug**

Players are teleported to each other’s faction homes.

---
**To Reproduce**
Two players must initiate the /mf home command at the same time.

---
**Expected behavior**
The players should teleport to their respective faction homes.

**Comment by dmccoystephenson** [comment]
A queuing system might be a potential solution to this problem. When implemented, players would be added to a queue when typing /mf home and would have to wait their turn before teleporting.

**Comment by dmccoystephenson** [comment]
This has not been verified to be fixed, but it might be fixed.

**Comment by alyphen** [comment]
This is the kind of issue caused by statefulness of commands, and is likely wider-reaching than solely home. All state should be removed from commands & listeners, and all required state should be kept within scope of the execution (i.e. scoped to onCommand in this case)
