### ISSUE TITLE
Fix duel challenges instantly starting a duel & players dying and losing their items upon losing an accepted duel.

### ISSUE THREAD

**Issue by DrGahora** [Dans-Plugins/Medieval-Factions#1326]
**Describe the bug**
/mf duel challenge (player name) instigates a duel without the other party accepting the challenge. The duel begins and allows both players to PvP and kill the losing party; dropping their grave which can be looted.

**To Reproduce**
type /mf duel challenge (player name you choose to challenge) proceed with PvP

**Expected behavior**
The other party (previously) was able to decline or accept the duel challenge, and the duel would not actually kill the player. Rather the winning party would receive the losing party's player head as a trophy

**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [x] 1.17.x
 - [ ] 1.18.x

**Comment by Mr-Deej** [comment]
@DrGahora can you please include the java version plugin version and spigot version

**Comment by dmccoystephenson** [comment]
> @DrGahora can you please include the java version plugin version and spigot version

@DrGahora is an admin on Kingdom: Unleashed, one of my servers. That server is using MF v4.6-alpha-2 and Spigot v1.17.1.

**Comment by dmccoystephenson** [comment]
I've just tested this on v4.6.1-alpha-1. The challenge issue is still present but the losing player does not die and lose their items anymore.

**Comment by dmccoystephenson** [comment]
Hey @philbgarner, would you be able to take a look at this when you have the chance? Some modifications I made awhile ago probably introduced this bug.

**Comment by dmccoystephenson** [comment]
I think the problem is in the DamageHandler class. We should at how damage was handled in prior versions of the plugin.
