### ISSUE TITLE
Fix players being able to interact with claimed pressure plates, levers and shulkers if their faction is at war the faction that has claimed those blocks.

### ISSUE THREAD

**Issue by Rocketsniper-1** [Dans-Plugins/Medieval-Factions#1350]
**Describe the bug**

---
**To Reproduce**

---
**Expected behavior**

---
**Screenshots or Logs**

---
**Java version**
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [ ] Java 17 
---
**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ ] v4.5.x
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [ ] 1.18.x

**Comment by Mr-Deej** [comment]
@Rocketsniper-1 can you please fill out the bug report thanks
