### ISSUE TITLE
Allied Factions API

### ISSUE THREAD

**Issue by Ajneb97** [Dans-Plugins/Medieval-Factions#1352]
What do you want the API call to do?
Implement an API to check the allies of a Factions, or if two factions are allied or not.

**Comment by dmccoystephenson** [comment]
This has been added and will be in the next release of Medieval Factions @Ajneb97

**Comment by Ajneb97** [comment]
How can I use it? Shouldn't be a method for the MF_Faction class to check for allies? Like MF_Faction.isAlly(String faction)

**Comment by dmccoystephenson** [comment]
@Ajneb97 
I just realized that the methods were added to the wrong location. This has been resolved. Check out this pre-release:
https://github.com/Dans-Plugins/Medieval-Factions/releases/tag/4.6.4-alpha-1
