### ISSUE TITLE
Factionless players are unable to hit players that have joined one.

### ISSUE THREAD

**Issue by kipper55** [Dans-Plugins/Medieval-Factions#1353]
**Describe the bug**

---
**To Reproduce**

---
**Expected behavior**

---
**Screenshots or Logs**

---
**Java version**
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [ ] Java 17 
---
**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ ] v4.5.x
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [ ] 1.18.x

**Comment by Mr-Deej** [comment]
@kipper55  can you please fill out the bug report sections
Java Version
Plugin Version
and Server Software version
Thank you
