### ISSUE TITLE
Bug Report - Not able to eat food in other faction's territory

### ISSUE THREAD

**Issue by Pomasto** [Dans-Plugins/Medieval-Factions#1358]
**Describe the bug**
You are not able to eat food in another faction's territory, regardless of your status as allies/enemies.

---
**To Reproduce**
1. Literally just try eating in a different faction's territory

---
**Expected behavior**
Food will continue with the eating noises and animation forever and won't actually eat

---
**Screenshots or Logs**
https://gyazo.com/514647234a99c56f5da3565c0406669e
https://gyazo.com/514647234a99c56f5da3565c0406669e)

---
**Java version**
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [X] Java 17 
---
**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ ] v4.5.x

v.4.6.2
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [X] 1.18.x
 
 Spigot 1.18.1

**Comment by dmccoystephenson** [comment]
Does this still occur when the player is looking at air and not a block?

**Comment by dmccoystephenson** [comment]
This should no longer be occurring in MF 5.
