### ISSUE TITLE
Factionless players can't PVP

### ISSUE THREAD

**Issue by SHadowofdar** [Dans-Plugins/Medieval-Factions#1384]
**Describe the bug**
players on my server cannot PvP when they are not in a faction
---
**To Reproduce**
have 2 factionless players in a world
have them try to pvp
---
**Expected behavior**
I expected them to be able to pvp
---
**Screenshots or Logs**

---
**Java version**
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [x] Java 17 
---
**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [x] v4.5.x
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [x] 1.18.x

**Comment by dmccoystephenson** [comment]
This has been resolved by #1385.
