### ISSUE TITLE
Fiefs.

### ISSUE THREAD

**Issue by Punchappy4** [Dans-Plugins/Medieval-Factions#1390]
Whenever someone tries making a Fief of my Faction, it says "you must be in a faction to use this command." 

The Fiefs plugin is installed and the flag to enableFiefs is true.

**Comment by dmccoystephenson** [comment]
Sorry to hear you're experiencing this, but thanks for letting us know! I'll try to take a look at this soon.

**Comment by dmccoystephenson** [comment]
The Fiefs plugin is in the process of being rewritten.
