### ISSUE TITLE
Fix Enderpearls still not dealing Damage

### ISSUE THREAD

**Issue by ethernia-root** [Dans-Plugins/Medieval-Factions#1392]
## Describe the bug
Enderpearls deal no Damage if Friendly Fire is disabled

## To Reproduce
Turn Friendly Fire off if it's not already,
Throw an Enderpearl

## Expected behavior
Enderpearls should deal Damage as normal

## Screenshots or Logs
https://i.imgur.com/D9XpM58.png

## Java version
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [x] Java 17 

**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [x] v4.5.x
---
**Paper version**
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [x] 1.18.x

**Comment by dmccoystephenson** [comment]
Thanks for letting us know about this!

**Comment by dmccoystephenson** [comment]
I'm not seeing anything that directly references ender pearls or the PlayerTeleportEvent class in the project, so this probably an unintended effect.
