### ISSUE TITLE
Cannot declare war

### ISSUE THREAD

**Issue by OMG67** [Dans-Plugins/Medieval-Factions#1394]
## Describe the bug
(A clear and concise description of what the bug is.)
When trying to declare war to a faction, it says "quotation marks are requiered" if I put them, if I don't, it just shows how to use the command. No matter if I put an existing faction or not, it gives the same error all the time.
## To Reproduce
(Steps to reproduce the behavior)
/mf dw/declarewar faction/"faction"/'faction'
## Expected behavior
(A clear and concise description of what you expected to happen.)
A war to be declared between my faction and the other faction.
## Screenshots or Logs
(If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/54108838/164983164-9867df08-0ed9-4bc5-a982-6aee4d0bbba0.png)
![image](https://user-images.githubusercontent.com/54108838/164983170-2810814c-1ad3-4189-9d73-4939064c2190.png)

## Java version
 - [ ] Java 8
 - [X ] Java 11
 - [ ] Java 16
 - [ ] Java 17 

**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ ] v4.5.x

None, it's marked as Medieval-Factions-4.6.4.jar
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [X ] 1.16.x
 - [ ] 1.17.x
 - [ ] 1.18.x

**Comment by OMG67** [comment]
Plugin version is not marked because it's none of those, it says it's 4.6.4

**Comment by dmccoystephenson** [comment]
Thanks for letting us know about this! I'll try to take a look soon.

**Comment by dmccoystephenson** [comment]
This has been resolved by #1395.
