### ISSUE TITLE
Make Worlds unclaimable

### ISSUE THREAD

**Issue by ethernia-root** [Dans-Plugins/Medieval-Factions#1398]
**Is your feature request related to a problem? Please describe.**
On my Server, the Nether and the End are anarcy. I added a rule that makes claiming land there illegal, but its still possible to do that.

**Describe the solution you'd like**
I would love to be able to make worlds unclaimable in the config!

**Comment by sujyrokimora** [comment]
Meanwhile you can use worldguard and block the command on the global region

**Comment by ethernia-root** [comment]
i havent thouht of that

**Comment by ethernia-root** [comment]
(workaround so closed)
