### ISSUE TITLE
Fix location of factions spamming the console in 1.19.

### ISSUE THREAD

**Issue by lbdamsma** [Dans-Plugins/Medieval-Factions#1400]
## Describe the bug
(A clear and concise description of what the bug is.)
In update 1.19 the location of the factions keeps spamming in the text tab.

## To Reproduce
(Steps to reproduce the behavior)
Enter in 1.19 a faction area

## Expected behavior
(A clear and concise description of what you expected to happen.)
No text spam .

## Screenshots or Logs
(If applicable, add screenshots to help explain your problem.)

## Java version
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [ x] Java 17 

**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ x] v4.5.x
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [ ] 1.18.x
 - [x] 1.19

**Comment by lbdamsma** [comment]
Issue still in the game with latest update

**Comment by dmccoystephenson** [comment]
> Issue still in the game with latest update

Thank you for the reminder! :)

**Comment by koenderey** [comment]
It can be temporary fixed by setting territoryAlertPopUp: to false.
but then there is also no big popup

**Comment by dmccoystephenson** [comment]
I'm not seeing any console prints near the code for sending territory alerts to players. I wonder what is causing this.

**Comment by dmccoystephenson** [comment]
Can you provide screenshots when you get the chance?
