### ISSUE TITLE
/mf home command blocks main thread

### ISSUE THREAD

**Issue by WNP78** [Dans-Plugins/Medieval-Factions#1405]
It seems that the delay for /mf home is waited twice - first, properly and asynchronously, but then once the asynchronous task runs it sleeps the thread for (default: 3) seconds. Since this is async, not multithreaded, this is the main server thread. It causes all clients connected to stop receiving packets for the entire teleport delay. Suggested fix is simply remove the extra sleep - the async task is already doing the delay. I can provide a video if required but it's fairly easy to reproduce - just make sure `teleportDelay` is over 0.

The extra delay I suggest removing is at:
https://github.com/Dans-Plugins/Medieval-Factions/blob/10394648a278d5781333d2dd86023da5e6bb9aef/src/main/java/dansplugins/factionsystem/utils/extended/Scheduler.java#L131

**Comment by dmccoystephenson** [comment]
Thank you for opening this issue and including the spot in the code. This change has been made.
