### ISSUE TITLE
Faction Flag Colors Documentation

### ISSUE THREAD

**Issue by Parzival-3141** [Dans-Plugins/Medieval-Factions#1406]
There doesn't seem to be any documentation on which color strings are valid for FactionFlags, in-game or on the wiki.
I'm pretty sure valid color strings are in [this file](https://github.com/Dans-Plugins/Medieval-Factions/blob/master/src/main/java/dansplugins/factionsystem/utils/ColorConversion.java). I'd make a PR on the wiki myself but github doesn't seem to really support this.

**Comment by dmccoystephenson** [comment]
Thanks for opening this issue! I think that this has confused people before. I can add it to the wiki :)

I'll copy the relevant file contents here as well:

        BLACK("#000000"), // Black
        DARK_BLUE("#151B8D"), // Denim Dark Blue
        DARK_GREEN("#254117"), // Dark Forest Green
        DARK_AQUA("#348781"), // Medium Aquamarine
        DARK_RED("#990012"), // Red Wine
        DARK_PURPLE("#461B7E"), // Purple Monster
        DARK_GRAY("#736F6E"), // Gray
        GOLD("#FDD017"), // Bright Gold
        GRAY("#B6B6B4"), // Gray Cloud
        BLUE("#1569C7"), // Blue Eyes
        GREEN("#41A317"), // Lime Green
        AQUA("#00FFFF"), // Cyan or Aqua
        RED("#FF0000"), // Red
        PURPLE("#FF00FF"), // Magenta
        YELLOW("#FFFF00"), // Yellow
        WHITE("#FFFFFF"), // White

**Comment by dmccoystephenson** [comment]
This has been added to this page of the Wiki:
https://github.com/Dans-Plugins/Medieval-Factions/wiki/Faction-Flags
