### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zeldaking** [Dans-Plugins/Medieval-Factions#1418]
How do you enable pvp for people of the same faction?

**Comment by dmccoystephenson** [comment]
The owner of the faction needs to set the relevant flag by typing the following:

> /mf set flag <flag name> <flag value>

Available flags can be viewed by typing the following:

/mf flags show

**Comment by dmccoystephenson** [comment]
At this time, also, there is no way to configure flags to have default values (except altering the code itself).
