### ISSUE TITLE
Force Unclaim command

### ISSUE THREAD

**Issue by GrapesMaster98** [Dans-Plugins/Medieval-Factions#1419]
**Is your feature request related to a problem? Please describe.**
Sometimes, my players claim zones that shouldn't be claimed, for example the spawn. One of my players got trapped inside a crater, another player then came, claimed that crater and trapped that player inside, since he was unable to break blocks, he was unable to leave (Staff had to tp him to safety)

**Describe the solution you'd like**
Add a /mf force unclaim command, so admins can unclaim zones that shouldn't be claimed.

I think that's all the context and info I can give, it's a command that would solve a lot of issues on my server and future issues on other servers.

**Comment by dmccoystephenson** [comment]
The changes in #1620 render this issue unnecessary as players can now unclaim the land of other factions when in bypass mode.
