### ISSUE TITLE
Fix translation keys not being found.

### ISSUE THREAD

**Issue by jackcayc924** [Dans-Plugins/Medieval-Factions#1508]
## Describe the bug
Some incompatibilities with the lang file

## To Reproduce
Compile mf 4.7.0 and run commands

## Expected behavior
Normal lang messages

## Screenshots or Logs
![image](https://user-images.githubusercontent.com/85153425/189207234-b5d1bdf4-27cc-41c0-a5ba-31b204d6f93e.png)

## Java version
 - [x] Java 17 

**Plugin version**
 - [x] 4.7.0
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
Paper
 - [x] 1.19.2

**Comment by jackcayc924** [comment]
I have my suspicions around LocaleService.java line 49, but after some debugging messages the logic seems fine..

**Comment by VoChiDanh** [comment]
do you think this error is caused by the language tsv file? Since the yml file doesn't have debug lines like this when I add it...

**Comment by dmccoystephenson** [comment]
It's possible @VoChiDanh, I haven't tried switching it to use the yml file yet.

**Comment by dmccoystephenson** [comment]
Tried switching to using the yml file, turns out it's empty when it's loaded into the plugin folder.
