### ISSUE TITLE
Feature Request - protectVillagerTrade flag

### ISSUE THREAD

**Issue by QuamCode** [Dans-Plugins/Medieval-Factions#1541]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

My Server heavily revolves around the use of custom villagers, population, villager jobs etc. What I would love to see is a native solution within the MF4 plugin, is a flag to restrict players from other factions trading with another factions villagers. Much like the MobProtection flag but just cancelling the interaction event on Villagers instead.

**Describe the solution you'd like**

Ideally: when protectVillagerTrade is True...
Player A in factions A is not allied with Player B in factions B. 
B comes into As territory. A has several hard to obtain Villagers that they have hired into their population. B tries to trade with the Villager but cannot because they are within As territory. If the Villager was in the Wilderness or the Villager was in Bs own or an allied territory, they could trade freely.

Vice versa, it would be unrestricted if set to false.

Main goal is to prevent non-allied players utilising the population of another faction.

**Describe alternatives you've considered**

I have tried assigning unique tags based on UUID to the villagers located within a certain radius of a marker (town center). However this Iis very clunky, works rarely and not ideal.

**Additional context**

Hrmmmm. Huh. Hrmmmm.

**Comment by dmccoystephenson** [comment]
Thanks for creating this issue!

**Comment by dmccoystephenson** [comment]
This will be in 5.2.0! 👍
