### ISSUE TITLE
More power to the API

### ISSUE THREAD

**Issue by nortoh** [Dans-Plugins/Medieval-Factions#1542]
Hello,

Curious as why there are not more features given to the MFApi such as access to wars a faction are in, and other features in the `Faction` class. I understand there's a deprecated `getUnderlyingImplementation`, which seems like it does give "the keys to the castle" for the factions, but the API should include more access.

If anything, I can just fork this and add my own, but I figured other developers might be wishing for the same in some regard.

**Comment by dmccoystephenson** [comment]
I've reopened this since the changes aren't in the master branch yet.

**Comment by dmccoystephenson** [comment]
Thanks for creating this issue! The API was very basic when it was created and it hasn't been expanded on too much. I'm very open to accepting changes from forks. Otherwise, I can get to this sometime in the future.

**Comment by nortoh** [comment]
Hello!

I appreciate the response. Would like to start off with saying how great of a plugin MF is. It has been a great alternative to the currently available plugins that are supported on Spigot.

Our main reason for the fork was primarily to do lots of cleanup/refactoring. We wanted to make changes for a personal server that we are running and we liked the base of what MF has to offer. It was more of a personal take rather than forking to make improvements to the main repo. For the changes we are looking to make, we feel that they will be too large to merge in and would change the overall structure of the main project. Therefore, we think it's best that we do not make PR's to the main repo. That being said, we do love improving open source projects and if you would like to take some changes from our fork, you're more than welcome to.

**Comment by dmccoystephenson** [comment]
I appreciate that! Forking the project to use it as a base and modifying it to suit your needs is encouraged, so go nuts. 

As far as PRs, go, contributors have changed the overall structure of the project before, but I understand the hesitation. You should feel no obligation to open PRs to the parent repository :)

You're welcome to rename your fork by the way, if you want to. Feel free to reach out on the discord server if you have any questions. I look forward to seeing how your fork diverges!
