### ISSUE TITLE
Fix players not being able to invoke allies to war.

### ISSUE THREAD

**Issue by sujyrokimora** [Dans-Plugins/Medieval-Factions#1615]
## Describe the bug
I cant invoke my allies to war

## To Reproduce
/mf invoke <factionname>

## Expected behavior
Send the request

## Screenshots or Logs
![image](https://user-images.githubusercontent.com/37046592/204060259-9fd6d084-b8a0-4e6f-9be3-7e10dca1cc1e.png)
![image](https://user-images.githubusercontent.com/37046592/204060270-6c174f0b-6ca2-44e5-a5b0-3fa67c8acb38.png)

## Java version
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [x] Java 17 

**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ ] v4.5.x
 - [x] 5.0.3
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [ ] 1.18.x
 - [x] 1.19.x

**Comment by dmccoystephenson** [comment]
This was fixed by commit 3b9214523f6c507563471aae43b82374935a9813.
