### ISSUE TITLE
Two factions can share the same name.

### ISSUE THREAD

**Issue by MrFoxMC** [Dans-Plugins/Medieval-Factions#1706]
Hello! I am loving the plugin and can't wait to see it in action on my server.

During testing, I noticed that two factions can share the same name.

This appears to break the /f declarewar command as well because when trying to enemy a faction that shares the same name as mine, I get: "There is no faction by that name".

Is there a way for me to disable the ability to create a faction using a name that is already taken?

![Screenshot 2023-04-02 041802](https://user-images.githubusercontent.com/106888731/229341031-62508e80-af38-429a-a557-4bebeb35fe00.png)

**Comment by dmccoystephenson** [comment]
It looks like we check for unique names when a faction is created but not when it is renamed. Thank you very much for creating this issue!

**Comment by dmccoystephenson** [comment]
This has been resolved. We'll get a patch release out soon :)
