### ISSUE TITLE
Bug Report: /lock basically softlocks you until you are able to lock something

### ISSUE THREAD

**Issue by ninjakitty844** [Dans-Plugins/Medieval-Factions#1707]
## Describe the bug
if you do /lock or /unlock, you are put into a state where you may select blocks to lock/unlock. you cannot break or place blocks while in this state. if you are not in a faction, then you get the error message "you must be in a faction to lock". there does not seem to be a command to cancel the locking/unlocking state, so you may not place or break blocks until you both join a faction AND find a block to lock/unlock that is in that faction's territory

## To Reproduce
type /lock or /unlock, be out of a faction or far from your faction's territory

## Expected behavior
best behavior would probably be for it to cancel the locking/unlocking state if you are not in a faction. or to not let you get into that state in the first place

## Screenshots or Logs
(If applicable, add screenshots to help explain your problem.)

## Java version
 - [ ] Java 8
 - [ ] Java 11
 - [ ] Java 16
 - [x ] Java 17 

**Plugin version**
 - [ ] v4.1
 - [ ] v4.2
 - [ ] v4.3
 - [ ] v4.4
 - [ ] v4.5.x
 - [ x] v5.1.3
---
**Spigot/Paper version** _(Please Specify which server software you are using)_
 - [ ] 1.16.x
 - [ ] 1.17.x
 - [ ] 1.18.x
 - [ x] 1.19.3

**Comment by MrFoxMC** [comment]
Hey! I came back to check on my own bug report and saw yours. You can actually do '/lock cancel' to cancel the action. Hope this helps! :)

**Comment by ninjakitty844** [comment]
Damn, I could've sworn that was the first thing I tried. But clearly not because it works!
