### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by CiodoxX** [Dans-Plugins/Medieval-Factions#1749]
The command /f promote shows like it doesn't exist. How can I promote to officer then? It doesn't send any errors or something in the logs, it just doesn't exist

**Comment by CarterMane** [comment]
You can do /f role set officer

**Comment by alyphen** [comment]
/f promote was removed in MF 5 in favour of the new role system, use the /mf role commands now (/f role create, /f role delete, /f role list, /f role rename, /f role set, /f role setdefault, /f role setpermission, /f role view)
